# .github/workflows/jira-issue-sync.yml

name: Create Jira Issue on GitHub Issue
permissions:
  contents: write
  issues: write
on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse a issue
        uses: stefanbuck/github-issue-praser@v3
        id: issue
        with:
          template-path: .github/ISSUE_TEMPLATE/default.yml

      - name: Print parsed values
        run: echo "${{ toJson(steps.issue.outputs) }}"

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Issue
        id: jira
        uses: atlassian/gajira-create@v3
        with:
          project: "NVS"
          issuetype: ${{ steps.issue.outputs.issueparser_jira_issuetype }}
          summary: "[${{ (github.event.issue.labels[0] && github.event.issue.labels[0].name) || 'chore' }}] ${{ github.event.issue.title }}"
          description: |
            ${{ steps.issue.outputs.issueparser_description }}
          fields: |
            {
              "parent": {
                "key": "${{ steps.issue.outputs.issueparser_parent_task }}"
              }
            }
      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[${{ steps.jira.outputs.issue }}] ${{ github.event.issue.title }}"

      - name: Create branch with ticket number
        id: branch
        run: |
          TICKET_NUMBER=${{ steps.jira.outputs.issue }}
          LABEL=${{ (github.event.issue.labels[0] && github.event.issue.labels[0].name) || 'chore'}}
          TITLE="${{ github.event.issue.title }}"
          FIT_TITLE=$(echo "${TITLE}" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | LC_ALL=C sed 's/[^a-z0-9가-힣-]//g')
          ISSUE_NUMBER=${{ github.event.issue.number }}
          BRANCH_NAME="${LABEL}/${TICKET_NUMBER}-${FIT_TITLE}#${ISSUE_NUMBER}"
          git checkout -b "${BRANCH_NAME}"
          git push origin "${BRANCH_NAME}"

          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Update Issue with Branch Name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.branch.outputs.branch_name }}"
          BODY="${{ github.event.issue.body }}"
          ISSUE_NUMBER=${{ github.event.issue.number }}

          # 2. 이슈 본문에 추가할 내용 구성
          NEW_CONTENT=$'\n\n'
          NEW_CONTENT+="---"$'\n'
          NEW_CONTENT+="### 작업 브랜치"$'\n'
          NEW_CONTENT+="${BRANCH_NAME}"

          # 3. 이슈 본문 업데이트
          gh issue edit $ISSUE_NUMBER --body "$BODY$NEW_CONTENT"

      - name: Change status to "In Progress"
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.jira.outputs.issue }}
          transition: "진행 중"
